language: d

dist: bionic

arch:
  - amd64
  - arm64

os:
  - osx
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then sudo apt-get install -y gcc-multilib ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then sudo apt-get install -y libc6-dev ; fi


# Note: LDC 1.27 requires GLIBC_2.27 and going with "dist: bionic" is not enough apprently
d:
 - ldc-1.26.0
 - ldc-1.24.0
 - dmd-2.097.0
 - dmd-2.094.2

matrix:
  allow_failures:
   - d: dmd-2.097.0
   - d: dmd-2.094.2

# uncompress encrypted VST SDK
before_install:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then openssl aes-256-cbc -K $encrypted_00660bf0ef48_key -iv $encrypted_00660bf0ef48_iv -in secrets-for-ci.tar.enc -out secrets-for-ci.tar -d ; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then tar xvf secrets-for-ci.tar ; fi

env:
  - VST2_SDK=$TRAVIS_BUILD_DIR/VST2_SDK

# Note: can't build dplug:vst2 in a pull request

script:
  - cd examples/distort; dub --compiler=${DC} -c LV2; cd ../..
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd examples/clipit; dub --compiler=${DC} -c VST2; cd ../.. ; fi
  - cd examples/ms-encode; dub --compiler=${DC} -c VST3; cd ../..
  - cd examples/arpejoe; dub --compiler=${DC} -c AU; cd ../..
  - cd examples/simple-mono-synth; dub --compiler=${DC} -c VST3; cd ../..
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd examples/poly-alias-synth; dub --compiler=${DC} -c VST2; cd ../.. ; fi
  - cd tools/dplug-build; dub --compiler=${DC}; cd ../..
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd tools/stress-plugin; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd tools/process; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd tools/latency-check; dub --compiler=${DC}; cd ../.. ; fi
  - cd tools/wav-compare; dub --compiler=${DC}; cd ../..
  - cd tools/wav-info; dub --compiler=${DC}; cd ../..
  - dub test --compiler=${DC} dplug:core
  - dub test --compiler=${DC} dplug:audio
  - dub test --compiler=${DC} dplug:math
  - dub test --compiler=${DC} dplug:dsp
  - dub test --compiler=${DC} dplug:fft
  - dub test --compiler=${DC} dplug:client
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then dub test --compiler=${DC} dplug:host ; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then dub test --compiler=${DC} dplug:vst2 ; fi
  - dub test --compiler=${DC} dplug:window
  - dub test --compiler=${DC} dplug:macos
  - dub test --compiler=${DC} dplug:au
  - dub test --compiler=${DC} dplug:pbr-widgets
  - dub test --compiler=${DC} dplug:flat-widgets
  - dub test --compiler=${DC} dplug:wren-support
  - dub test --compiler=${DC} dplug:lv2
  - dub test --compiler=${DC} dplug:vst3
  - dub test --compiler=${DC} dplug:graphics
  - dub test --compiler=${DC} dplug:canvas
  - dub test --compiler=${DC} -b unittest-release dplug:core
  - dub test --compiler=${DC} -b unittest-release dplug:dsp
  - dub test --compiler=${DC} -b unittest-release dplug:fft
