language: d

arch:
  - amd64
  - arm64

os:
  - osx
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then sudo apt-get install -y gcc-multilib ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then sudo apt-get install -y libc6-dev ; fi

# TODO: 32-bit testing...

d:
 - ldc-beta
 - ldc-1.26.0
 - ldc-1.25.1
 - ldc-1.24.0
 - dmd-beta
 - dmd-2.097.0
 - dmd-2.096.1
 - dmd-2.095.1
 - dmd-2.094.2

matrix:
  allow_failures:
   - d: dmd-beta
   - d: dmd-2.097.0
   - d: dmd-2.096.1
   - d: dmd-2.095.1
   - d: dmd-2.094.2

# uncompress encrypted VST SDK
before_install:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then openssl aes-256-cbc -K $encrypted_00660bf0ef48_key -iv $encrypted_00660bf0ef48_iv -in secrets-for-ci.tar.enc -out secrets-for-ci.tar -d ; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then tar xvf secrets-for-ci.tar ; fi

env:
  - VST2_SDK=$TRAVIS_BUILD_DIR/VST2_SDK

script:
  - cd examples/distort; dub --compiler=${DC} -c LV2; cd ../..
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd examples/clipit; dub --compiler=${DC} -c VST2; cd ../.. ; fi
  - cd examples/ms-encode; dub --compiler=${DC} -c VST3; cd ../..
  - cd examples/simple-mono-synth; dub --compiler=${DC} -c VST3; cd ../..
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd examples/poly-alias-synth; dub --compiler=${DC} -c VST2; cd ../.. ; fi
  - cd tools/dplug-build; dub --compiler=${DC}; cd ../..
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd tools/stress-plugin; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd tools/process; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd tools/latency-check; dub --compiler=${DC}; cd ../.. ; fi
  - cd tools/wav-compare; dub --compiler=${DC}; cd ../..
  - cd tools/wav-info; dub --compiler=${DC}; cd ../..
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then cd examples/distort; dub --compiler=${DC} -a x86; cd ../.. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then cd examples/clipit; dub --compiler=${DC} -a x86; cd ../.. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then cd examples/ms-encode; dub --compiler=${DC} -a x86; cd ../.. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then cd examples/simple-mono-synth; dub --compiler=${DC} -a x86; cd ../.. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then cd examples/poly-alias-synth; dub --compiler=${DC} -a x86; cd ../.. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then cd tools/dplug-build; dub --compiler=${DC} -a x86; cd ../.. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd tools/stress-plugin; dub --compiler=${DC} -a x86; cd ../.. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd tools/process; dub --compiler=${DC} -a x86; cd ../.. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then cd tools/latency-check; dub --compiler=${DC} -a x86; cd ../.. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then cd tools/wav-compare; dub --compiler=${DC} -a x86; cd ../.. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then cd tools/wav-info; dub --compiler=${DC} -a x86; cd ../.. ; fi
  - dub test --compiler=${DC} dplug:core
  - dub test --compiler=${DC} dplug:math
  - dub test --compiler=${DC} dplug:dsp
  - dub test --compiler=${DC} dplug:fft
  - dub test --compiler=${DC} dplug:client
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then dub test --compiler=${DC} dplug:host ; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then dub test --compiler=${DC} dplug:vst2 ; fi
  - dub test --compiler=${DC} dplug:window
  - dub test --compiler=${DC} dplug:macos
  - dub test --compiler=${DC} dplug:au
  - dub test --compiler=${DC} dplug:pbr-widgets
  - dub test --compiler=${DC} dplug:flat-widgets
  - dub test --compiler=${DC} dplug:lv2
  - dub test --compiler=${DC} dplug:vst3
  - dub test --compiler=${DC} dplug:graphics
  - dub test --compiler=${DC} dplug:canvas
  - dub test --compiler=${DC} -b unittest-release dplug:core
  - dub test --compiler=${DC} -b unittest-release dplug:dsp
  - dub test --compiler=${DC} -b unittest-release dplug:fft
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:core ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:math ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:dsp ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:fft ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then dub test --compiler=${DC} -a x86 dplug:client ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then dub test --compiler=${DC} -a x86 dplug:host ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:vst2 ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:window ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:macos ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:au ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:pbr-widgets ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:flat-widgets ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:lv2 ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:vst3 ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:graphics ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 dplug:canvas ; fi