dub test dplug:core
dub test dplug:math
dub test dplug:dsp
dub test dplug:fft
dub test dplug:client
dub test dplug:host
dub test dplug:vst2
dub test dplug:window
dub test dplug:macos
dub test dplug:au
dub test dplug:pbr-widgets
dub test dplug:flat-widgets
dub test dplug:lv2
dub test dplug:vst3
dub test dplug:graphics
dub test dplug:canvas
dub test dplug:wren-support
dub test dplug:flp
dub test dplug:clap
