dub test :core
dub test :math
dub test :dsp
dub test :fft
dub test :formats
dub test :client
dub test :host
dub test :vst2
dub test :window
dub test :macos
dub test :pbr-widgets
dub test :flat-widgets
dub test :graphics
dub test :canvas
dub test :wren-support
